name: Lint

on:
  push:
    branches:
      - preflight

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Run lint
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
        run: deno lint
